name: Tag and release
on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.22.0
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          max_commits: 1
